version: '3.7'

services:
  mysql:
    container_name: mysql-server
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mall
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mall-network

  redis:
    container_name: redis-server
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mall-network  
  
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=tzq
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mall-network

  mall:
    container_name: mall-server 
    build: "."
    restart: always
    ports:
      - "8000:8000"
    networks:
      - mall-network
    depends_on:
      - mysql 
      - redis
      - rabbitmq


  
volumes:
  mysql-data:
  rabbitmq-home:

networks:
  mall-network:
    driver: bridge